[package]
name = "BulbaTV"
version = "0.1.0"
edition = "2024"
authors = ["https://github.com/vladimir2090"]

[dependencies]
tokio = "1.40.0"
lava_torrent = "0.11.1"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
hex = "0.4.3"
sha1 = "0.10.6"
anyhow = "1.0.99"