path_torrent: "C:/Users/admin/Desktop/torrent_folder/Avengers Endgame [2019, Фантастика, боевик, приключения, BDRip 1080p] [rutracker-6589921].torrent"
# disk_space: ""  # Uncomment and set disk space limit when needed